### ISSUE TITLE
target. Semangat

### ISSUE THREAD

**Issue by muhrifat** [stevenkur/FPprogjar#1]
- [x] Membuat aplikasi FTP klien dan server
- [x] Autentikasi (USER 
- [x] dan PASS: 4.1.1)
- [x] Mengubah direktori aktif (CWD: 4.1.1)
- [x] Keluar aplikasi (QUIT: 4.1.1)
- [x] Unduh (RETR: 4.1.3)
- [x] Unggah (STOR: 4.1.3)
- [x] Mengganti nama file (RNTO: 4.1.3)
- [x] Menghapus file (DELE: 4.1.3) 
- [x] Menghapus direktori (RMD: 4.1.3)
- [x] Membuat direktori (MKD: 4.1.3)
- [x] Mencetak direktori aktif (PWD: 4.1.3)
- [x] Mendaftar file dan direktori (LIST: 4.1.3)
- [x] HELP: 4.1.3
- [x] Reply codes (200, 
- [x] 500,
- [x]  230,
- [x]  530: 4.2.1)
- [x] Menerapkan teknik multiclient dengan modul select DAN thread

**Comment by rey09** [comment]
ayo kurang dikit lagi guys

**Comment by muhrifat** [comment]
jangan lupa di isi rek wkwk



> muda kaya mati masuk surga

**Comment by sektibayu** [comment]
udah begadang lagi hari ini

**Comment by stevenkur** [comment]
Semangat
